//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyToWordsServer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyToWordsResult", Namespace="http://schemas.datacontract.org/2004/07/CurrencyToWordsServer")]
    public partial class CurrencyToWordsResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string errorCodeField;
        
        private string resultInWordsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultInWords
        {
            get
            {
                return this.resultInWordsField;
            }
            set
            {
                this.resultInWordsField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICurrencyToWordsConverter")]
public interface ICurrencyToWordsConverter
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyToWordsConverter/CurrencyToWords", ReplyAction="http://tempuri.org/ICurrencyToWordsConverter/CurrencyToWordsResponse")]
    CurrencyToWordsServer.CurrencyToWordsResult CurrencyToWords(double amountInDigits);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyToWordsConverter/CurrencyToWords", ReplyAction="http://tempuri.org/ICurrencyToWordsConverter/CurrencyToWordsResponse")]
    System.Threading.Tasks.Task<CurrencyToWordsServer.CurrencyToWordsResult> CurrencyToWordsAsync(double amountInDigits);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICurrencyToWordsConverterChannel : ICurrencyToWordsConverter, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CurrencyToWordsConverterClient : System.ServiceModel.ClientBase<ICurrencyToWordsConverter>, ICurrencyToWordsConverter
{
    
    public CurrencyToWordsConverterClient()
    {
    }
    
    public CurrencyToWordsConverterClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CurrencyToWordsConverterClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CurrencyToWordsConverterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CurrencyToWordsConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CurrencyToWordsServer.CurrencyToWordsResult CurrencyToWords(double amountInDigits)
    {
        return base.Channel.CurrencyToWords(amountInDigits);
    }
    
    public System.Threading.Tasks.Task<CurrencyToWordsServer.CurrencyToWordsResult> CurrencyToWordsAsync(double amountInDigits)
    {
        return base.Channel.CurrencyToWordsAsync(amountInDigits);
    }
}
